edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: functionApp       #  项目名称
access: aliyun-release  #  秘钥别名

services:
  function-test: #  服务名称
    component: web-express  # 组件名称
    deploy:
      - Hook: npm install --production
        Path: ./code
        Pre: true
    props: #  组件的属性值
      region: cn-shenzhen
      service:
        name: app-express
      function:
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/test-wss/nodejs12:v0.1
          command: '["node", "index.js"]'
        code:
          src: ./code